version: '3'
services:
  fsmysql:
    image: mysql:5.7.27
    container_name: fs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password
    volumes:
      - /opt/formshare/mysql:/var/lib/mysql
    networks:
      fsnet:
        ipv4_address: 172.28.1.5
  
  fselasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: fs_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - network.host=172.28.1.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/formshare/elasticsearch/esdata:/usr/share/elasticsearch/data
    networks:
      fsnet:
        ipv4_address: 172.28.1.1
  fselasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: fs_elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=172.28.1.2
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.zen.ping.unicast.hosts=172.28.1.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/formshare/elasticsearch/esdata2:/usr/share/elasticsearch/data
    networks:
      fsnet:
        ipv4_address: 172.28.1.2
  fselasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: fs_elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=172.28.1.3
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.zen.ping.unicast.hosts=172.28.1.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/formshare/elasticsearch/esdata3:/usr/share/elasticsearch/data
    networks:
      fsnet:
        ipv4_address: 172.28.1.3
  formshare:
    image: qlands/formshare2:20200426
    container_name: formshare
    environment:
      MYSQL_HOST_NAME: 172.28.1.5
      MYSQL_USER_NAME: root
      MYSQL_USER_PASSWORD: my_secure_password
      FORMSHARE_ADMIN_USER: admin
      FORMSHARE_ADMIN_EMAIL: admin@myserver.com
      FORMSHARE_ADMIN_PASSWORD: my_secure_password
      ELASTIC_SEARCH_HOST: 172.28.1.1
      ELASTIC_SEARCH_PORT: 9200
      FORMSHARE_HOST: 172.28.1.4
      FORMSHARE_PORT: 5900
      FORWARDED_ALLOW_IP: 172.28.1.4
      CONFIGURE_FLUENT: "true"
      WAIT_HOSTS: 172.28.1.5:3306, 172.28.1.1:9200
      WAIT_HOSTS_TIMEOUT: 120
    volumes:
      - /opt/formshare/repository:/opt/formshare_repository
      - /opt/formshare/log:/opt/formshare_log
      - /opt/formshare/celery:/opt/formshare_celery
      - /opt/formshare/config:/opt/formshare_config
      - /opt/formshare/fluentd:/opt/formshare_fluentd
      - /opt/formshare/plugins:/opt/formshare_plugins
      - fsokdtools:/opt/odktools
      - fssource:/opt/formshare
    ports:
      - 5900:5900
    networks:
      fsnet: 
        ipv4_address: 172.28.1.4

  fsfluentd:
    image: qlands/fluentd:v1.7.3-1.0
    container_name: fsfluentd
    environment:
      WAIT_HOSTS: 172.28.1.1:9200, 172.28.1.4:5900
      WAIT_HOSTS_TIMEOUT: 120
    volumes:
      - /opt/formshare/log:/opt/formshare_log
      - /opt/formshare/fluentd:/fluentd/etc/
    networks:
      fsnet:
        ipv4_address: 172.28.1.6

  fskibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: fskibana
    environment:
      ELASTICSEARCH_URL: http://172.28.1.1:9200
    ports:
      - 5601:5601
    networks:
      - fsnet
      
networks:
  fsnet:
     ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16

volumes:
  fsokdtools:
    driver: local
  fssource:
    driver: local